# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  envoygateway:
    image: envoygateway
    build: 
      context: .
      dockerfile: Gateways/Envoy/Dockerfile
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
  catalogservice:
    image: catalogservice
    build:
      context: .
      dockerfile: Services/CatalogService/Dockerfile
# Direct, external access to API within composed environment
    ports:
      - 8080:80
      - 8081:443
  coffeeapi:
    image: coffeeapi
    build:
      context: .
      dockerfile: Services/Coffee/Coffee.API/Dockerfile
# Hide direct external access to the container
# Gateway provides routed access within the composed environment
#    ports:
#      - 8082:80
#      - 8083:443
  teaapi:
    image: teaapi
    build:
      context: .
      dockerfile: Services/Tea/Tea.API/Dockerfile
# Hide direct external access to the container
# Gateway provides routed access within the composed environment
#    ports:
#      - 8084:80
#      - 8085:443
