name: Build and deploy .NET application to container app mg-catalogservice-api
on:
  push:
    branches:
    - main
# Added permission to support Azure login using OIDC
permissions:
  id-token: write
env:
  CONTAINER_APP_CONTAINER_NAME: mg-main-container
  CONTAINER_APP_NAME: mg-catalogservice-api
  CONTAINER_APP_RESOURCE_GROUP_NAME: MelloGee
  CONTAINER_REGISTRY_LOGIN_SERVER: mellogeeacr.azurecr.io
  DOCKER_FILE_PATH: Services/CatalogService/Dockerfile
  PROJECT_NAME_FOR_DOCKER: catalogservice
  CONTAINER_APPS_ENVIRONMENT: mg-container-env
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout to the branch
      uses: actions/checkout@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
#    - 
#      name: Login to Azure container registry
#      uses: docker/login-action@v1
#      with:
#        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
#        username: ${{ secrets.mellogeeacr_USERNAME_9A5D }}
#        password: ${{ secrets.mellogeeacr_PASSWORD_9A5D }}
    - # Added for switch to using Docker Hub container registry
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Login to Docker Hub container registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    - 
#      name: Build and push image to Azure registry
#      uses: docker/build-push-action@v2
#      with:
#        push: true
#        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
#        file: ${{ env.DOCKER_FILE_PATH }}
    - 
      name: Build and push image to Docker Hub registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    # Set Git Environments
    environment: dev
    needs: build
    steps:
# Login to Azure using App Registration and ClientSecret
#    - name: Azure Login
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.mg_catalogservice_api_SPN }}
# Login to Azure using OIDC
# https://colinsalmcorner.com/actions-authenticate-to-azure-without-a-secret/ 
    # ubuntu Az CLI installation 
    - name: Install CLI-beta
      run: |
        cd ../..
        CWD="$(pwd)"
        python3 -m venv oidc-venv
        . oidc-venv/bin/activate
        echo "activated environment" 
        python3 -m pip install --upgrade pip
        echo "started installing cli beta" 
        pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
        echo "installed cli beta"    
        echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH   
    - name: 'Az CLI login'
      uses: azure/login@v1.4.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        # Depoy from Azure Container Registry
#        inlineScript: >
#          az config set extension.use_dynamic_install=yes_without_prompt
#          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.mellogeeacr_USERNAME_9A5D }} --password ${{ secrets.mellogeeacr_PASSWORD_9A5D }}
#          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        # Depoy from Docker Hub Container Registry
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }} --environment ${{ env.CONTAINER_APPS_ENVIRONMENT }} --registry-username ${{ secrets.DOCKERHUB_USERNAME}} --registry-password ${{ secrets.DOCKERHUB_TOKEN}} --registry-server hub.docker.com 
          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ secrets.DOCKERHUB_USERNAME}}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
